import type { ProductItem } from './types';

export const PRODUCTS: ProductItem[] = [
  {
    id: 'newsletter-playbook-founders',
    title: 'The Newsletter Playbook for Founders',
    category: 'Digital Products',
    description: 'The exact playbook used to scale Morning Brew to 4M subscribers and build Big Desk Energy to 100K+ subscribers generating $500K+ per year.',
    author: 'Big Desk Energy',
    url: 'https://mail.bigdeskenergy.com/products/the-newsletter-playbook-for-founders',
    tags: ['Newsletter', 'Playbook', 'Founders'],
    date: '2024-01-15',
  },
  {
    id: 'naked-newsletter-accelerator',
    title: 'Naked Newsletter Accelerator',
    category: 'Digital Products',
    description: 'Launch your newsletter in 4 weeks with step-by-step guidance from Kristin Kenzy. A structured program to accelerate your newsletter launch.',
    author: 'Drunk Business Advice',
    url: 'https://www.drunkbusinessadvice.co/products/naked-newsletter-accelerator',
    tags: ['Newsletter', 'Course'],
    date: '2026-01-30',
  },
  {
    id: 'new-translation-torah',
    title: 'A New Translation of the Torah',
    category: 'Digital Products',
    description: 'A fresh, faithful translation of the Five Books of Moses with translator\'s notes, cultural annotations, and literary analysis to engage with Scripture through an ancient Israelite perspective.',
    author: 'Taylor Halverson, Ph.D.',
    url: 'https://insights.taylorhalverson.com/products/a-new-translation-of-the-torah-genesis-exodus-leviticus-numbers-deuteronomy-by-taylor-halverson-ph-d',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'mistakes-mainstream-management',
    title: 'Mistakes of Mainstream Management',
    category: 'Digital Products',
    description: 'A provocative critique of industrial-era management practices with systems thinking principles that challenge leaders to view organizations as complex socio-technical systems.',
    author: 'Cyb3rSyn Labs',
    url: 'https://www.cyb3rsyn.com/products/mmm-book',
    tags: ['Ebook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'connecting-the-dots',
    title: 'Connecting the Dots',
    category: 'Digital Products',
    description: 'Explores the Toyota Production System beyond surface-level concepts, examining the origins and the "why" behind Just-in-Time, Jidoka, Continuous Improvement, and Respect for People.',
    author: 'Cyb3rSyn Labs',
    url: 'https://www.cyb3rsyn.com/products/connecting-the-dots-book',
    tags: ['Ebook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'second-order-cybernetics',
    title: 'Second Order Cybernetics: Essays for Silicon Valley',
    category: 'Digital Products',
    description: 'Explores foundational principles of second-order cybernetics, examining how observers impact systems. Covers thinkers like Ross Ashby, Heinz von Foerster, and Stafford Beer.',
    author: 'Cyb3rSyn Labs',
    url: 'https://www.cyb3rsyn.com/products/soc-book',
    tags: ['Ebook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'systems-thinker-enterprise-architecture',
    title: 'A Systems Thinker\'s View of Enterprise Architecture',
    category: 'Digital Products',
    description: 'First in a four-part series presenting enterprise architecture for corporations seeking to standardize, integrate, optimize and innovate in business processes.',
    author: 'Graham Berrisford',
    url: 'https://www.cyb3rsyn.com/products/stv-ea-book',
    tags: ['Ebook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'systems-thinker-description-reality',
    title: 'A Systems Thinker\'s View of Description and Reality',
    category: 'Digital Products',
    description: 'Discusses how we describe things by symbolizing, likening, categorizing and relating them. Explores causality, determinism, free will, and assembles a new world view.',
    author: 'Graham Berrisford',
    url: 'https://www.cyb3rsyn.com/products/stv-da-book',
    tags: ['Ebook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'systems-thinker-systems-thinkers',
    title: 'A Systems Thinker\'s View of Systems Thinkers',
    category: 'Digital Products',
    description: 'Compares and contrasts ideas from Ackoff, Ashby, Beer, Bertalanffy, Checkland, Forrester, Maturana, Meadows, Senge and more with unique insights.',
    author: 'Graham Berrisford',
    url: 'https://www.cyb3rsyn.com/products/stv-st-book',
    tags: ['Ebook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'systems-thinker-sociology',
    title: 'A Systems Thinker\'s View of Sociology',
    category: 'Digital Products',
    description: 'Examines Social Systems, Socioeconomics, and Social History, exploring how policies with good intentions frequently result in unintended consequences.',
    author: 'Graham Berrisford',
    url: 'https://www.cyb3rsyn.com/products/stv-so-book',
    tags: ['Ebook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'chatgpt-baby-boomers-images',
    title: 'ChatGPT for Baby Boomers - Complete Learning Bundle',
    category: 'Digital Products',
    description: 'A digital learning resource designed to teach ChatGPT and AI concepts to Baby Boomers through an illustrated PDF format.',
    author: '65Nation',
    url: 'https://newsletter.65nation.com/products/chatgpt-for-baby-boomers-pdf-with-images',
    tags: ['Ebook', 'AI'],
    date: '2026-01-30',
  },
  {
    id: 'chatgpt-baby-boomers-classic',
    title: 'ChatGPT for Baby Boomers - Classic PDF',
    category: 'Digital Products',
    description: 'An educational digital product designed to teach older adults how to use ChatGPT and AI technology. Classic PDF format without images.',
    author: '65Nation',
    url: 'https://newsletter.65nation.com/products/chatgpt-for-baby-boomers-classic-pdf-no-images',
    tags: ['Ebook', 'AI'],
    date: '2026-01-30',
  },
  {
    id: 'chatgpt-seniors-text-only',
    title: 'ChatGPT for Seniors - Text-Only PDF Guide',
    category: 'Digital Products',
    description: 'A text-only PDF guide specifically designed for seniors learning to use ChatGPT technology.',
    author: '65Nation',
    url: 'https://newsletter.65nation.com/products/text-only-pdf-chatgpt-for-seniors',
    tags: ['Ebook', 'AI'],
    date: '2026-01-30',
  },
  {
    id: '5-stages-cold-outreach-creatives',
    title: 'The 5 Stages of Cold Outreach for Creatives',
    category: 'Digital Products',
    description: 'A framework for reaching out to dream clients without sounding like everyone else. Built for photographers, directors, producers, and creative entrepreneurs.',
    author: 'Chris Whitten',
    url: 'https://bychriswhitten.beehiiv.com/products/the-5-stages-of-cold-outreach-for-creatives',
    tags: ['Playbook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: '6-maps-4-itineraries',
    title: '6 Maps & 4 Itineraries',
    category: 'Digital Products',
    description: 'A Notion Page with 6 Thailand Maps & 4 Itineraries (PDF files) for planning your Thailand trip.',
    author: 'Tim Travel Taste',
    url: 'https://timtraveltaste.beehiiv.com/products/6-maps-4-itineraries',
    tags: ['Template', 'Travel'],
    date: '2026-01-30',
  },
  {
    id: 'thailand-ai-tool-box',
    title: 'Thailand AI Tool Box',
    category: 'Digital Products',
    description: '13 Thailand-specific AI tools to save planning time and avoid costly mistakes. Includes 10 web apps and 3 Custom GPTs.',
    author: 'Tim Travel Taste',
    url: 'https://timtraveltaste.beehiiv.com/products/thailand-ai-tool-box',
    tags: ['Template', 'Travel'],
    date: '2026-01-30',
  },
  {
    id: 'maps-itineraries-big-pack',
    title: '23 Maps & 20 Itineraries (Big Pack)',
    category: 'Digital Products',
    description: 'A Notion Page containing 23 custom Google Maps and 20 ready-to-book Thailand travel itineraries.',
    author: 'Tim Travel Taste',
    url: 'https://timtraveltaste.beehiiv.com/products/maps-itineraries-big-pack',
    tags: ['Template', 'Travel'],
    date: '2026-01-30',
  },
  {
    id: 'thailand-trip-os',
    title: 'Thailand Trip OS',
    category: 'Digital Products',
    description: 'A comprehensive Notion-based planning system with 1000+ tips, 50+ guide pages, 40+ custom Google Maps, 20 itineraries, and 14 AI tools.',
    author: 'Tim Travel Taste',
    url: 'https://timtraveltaste.beehiiv.com/products/thailand-trip-os',
    tags: ['Template', 'Travel'],
    date: '2026-01-30',
  },
  {
    id: 'distilled-playbook-collection',
    title: 'DistillED Playbook Collection (Editions 1–3)',
    category: 'Digital Products',
    description: 'A practical bundle combining all three DistillED Playbooks with high-impact, evidence-informed teaching strategies.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/distilled-playbook-full-collection',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'distilled-playbook-edition3',
    title: 'DistillED Playbook (Edition 3)',
    category: 'Digital Products',
    description: 'A practical playbook distilling high-impact, evidence-informed teaching routines that make student thinking visible.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/distilled-playbook-edition3',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'distilled-playbook-edition2',
    title: 'DistillED Playbook (Edition 2)',
    category: 'Digital Products',
    description: 'Six high-impact, evidence-informed teaching routines that make student thinking visible and support responsive instruction.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/distilled-playbook-edition2',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'distilled-playbook-edition1',
    title: 'DistillED Playbook (Edition 1)',
    category: 'Digital Products',
    description: 'Six high-impact, evidence-informed teaching strategies grounded in learning and memory research.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/distilled-playbook-edition1',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'strategy-call-45-minutes',
    title: 'Strategy Call (45 minutes)',
    category: 'Digital Products',
    description: 'A focused 1:1 strategy call to clarify a teaching or professional development challenge with clear, actionable next steps.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/strategy-call-45-minutes',
    tags: ['Course', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'retrieval-practice-review',
    title: 'Retrieval Practice and Review',
    category: 'Digital Products',
    description: 'A ready-to-run CPD collection focused on retrieval practice and review, helping teachers strengthen memory and make learning stick.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/retrieval-practice-and-review',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'explanation-clarity-cpd',
    title: 'Explanation and Clarity CPD Collection',
    category: 'Digital Products',
    description: 'Help educators communicate complex concepts effectively through storytelling, worked examples, and visual modelling.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/explanation-and-clarity-cpd-collection',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'review-practice-cpd',
    title: 'Review and Practice CPD Collection',
    category: 'Digital Products',
    description: 'A ready-to-run CPD collection focused on systematic review and daily/weekly practice to strengthen long-term retention.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/review-and-practice-cpd-collection',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'attention-classroom-culture-cpd',
    title: 'Attention and Classroom Culture CPD Collection',
    category: 'Digital Products',
    description: 'Establish routines and expectations that create calm and focused learning environments.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/attention-and-classroom-culture-cpd-collection',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'participation-thinking-cpd',
    title: 'Participation and Thinking CPD Collection',
    category: 'Digital Products',
    description: 'Engage every student in purposeful talk, retrieval, and shared thinking. Extra PDF included!',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/participation-and-thinking-cpd-collection',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'feedback-responsive-teaching',
    title: 'Feedback and Responsive Teaching',
    category: 'Digital Products',
    description: 'A ready-to-run CPD collection helping teachers respond to learning in the moment and improve outcomes through actionable feedback.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/feedback-and-responsive-teaching',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'practice-scaffolding-cpd',
    title: 'Practice and Scaffolding CPD Collection',
    category: 'Digital Products',
    description: 'Instructional techniques that break learning into manageable steps while supporting students toward independent success.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/practice-and-scaffolding-cpd-collection',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'checking-understanding-cpd',
    title: 'Checking for Understanding CPD Collection',
    category: 'Digital Products',
    description: 'Diagnose learning in real time and respond effectively through hinge questions and exit tickets.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/checking-for-understanding-cpd-collection',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'questioning-participation-cpd',
    title: 'Questioning and Participation CPD Collection',
    category: 'Digital Products',
    description: 'Involve every student through effective questioning techniques, cold calling strategies, and wait time implementation.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/questioning-and-participation-cpd-collection',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'instruction-modelling-cpd',
    title: 'Instruction and Modelling CPD Collection',
    category: 'Digital Products',
    description: 'Support teachers to explain, demonstrate, and sequence learning effectively.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/instruction-and-modelling-cpd-collection',
    tags: ['Playbook', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'inclusive-teaching-checking-understanding',
    title: 'Inclusive Teaching & Checking Understanding',
    category: 'Digital Products',
    description: 'A practical PDF collection focused on inclusive teaching — from equitable questioning to checking understanding in real time.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/inclusive-teaching-checking-understanding',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'attention-hard-thinking',
    title: 'Attention & Hard Thinking',
    category: 'Digital Products',
    description: 'A practical PDF collection focused on securing attention and promoting hard thinking — from attention cues to recognising genuine evidence of learning.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/attention-hard-thinking',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'responsive-teaching-feedback',
    title: 'Responsive Teaching & Feedback',
    category: 'Digital Products',
    description: 'A practical PDF collection focused on responsive teaching — from checking understanding to adapting instruction and feedback in real time.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/responsive-teaching-feedback',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'reducing-cognitive-load',
    title: 'Reducing Cognitive Load',
    category: 'Digital Products',
    description: 'A practical PDF collection covering how the mind learns, modelling techniques, worked examples, and clear explanations.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/reducing-cognitive-load',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'foundations-explicit-instruction',
    title: 'Foundations of Explicit Instruction',
    category: 'Digital Products',
    description: 'A practical PDF collection spanning clear explanations and modelling to active participation and worked examples.',
    author: 'Jamie Lee Clark',
    url: 'https://newsletter.jamieleeclark.com/products/foundations-of-explicit-instruction',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'shield-index-january-2026',
    title: 'The Shield Index — January 2026',
    category: 'Digital Products',
    description: 'LinkedIn market intelligence explaining the December Downshift with updated reach and format benchmarks.',
    author: 'The Shield Index',
    url: 'https://theshieldindex.beehiiv.com/products/the-shield-index-january-2026',
    tags: ['Ebook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'fais-2026',
    title: 'Financial Astrology Investment Selections 2026',
    category: 'Digital Products',
    description: 'Sama\'s Chosen Stocks, Sectors and ETFs for 2026 + Video on Market Timing.',
    author: 'Sama',
    url: 'https://sama.beehiiv.com/products/fais-2026',
    tags: ['Ebook', 'Finance'],
    date: '2026-01-30',
  },
  {
    id: 'culture-clarity-session',
    title: 'Culture Clarity Session',
    category: 'Digital Products',
    description: 'A 60-minute strategic consultation to transform organizational culture with clear systems, messaging frameworks, and a 30-day implementation plan.',
    author: 'The Growth Compass',
    url: 'https://thegrowthcompass.beehiiv.com/products/strategy-session-with-aj',
    tags: ['Course', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'mental-fitness-youth-consult',
    title: 'Free Consult - Mental Fitness (Youth)',
    category: 'Digital Products',
    description: 'Help youth develop mental fitness to thrive. A consultation for children struggling with confidence or pressure.',
    author: 'The Growth Compass',
    url: 'https://thegrowthcompass.beehiiv.com/products/free-consult-mental-fitness-youth',
    tags: ['Course', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'daily-coach-system',
    title: 'The Daily Coach System',
    category: 'Digital Products',
    description: '26 championship systems from the winningest coaches, leaders, and sports psychologists delivered in 30 days. 5 minutes a day.',
    author: 'The Growth Compass',
    url: 'https://thegrowthcompass.beehiiv.com/products/the-daily-coach-system',
    tags: ['Course', 'Teaching'],
    date: '2026-01-30',
  },
  {
    id: 'power-prompts-pro-pack',
    title: 'Power Prompts Pro Pack',
    category: 'Digital Products',
    description: '850+ prompts across 20+ domains, 850+ custom GPTs, 500+ free AI courses, prompt engineering guide, and more.',
    author: 'Power Prompts',
    url: 'https://powerprompts.beehiiv.com/products/powerpromptspro',
    tags: ['Template', 'AI'],
    date: '2026-01-30',
  },
  {
    id: 'financial-mastery-prompt-bundle',
    title: 'Financial Mastery Prompt Bundle',
    category: 'Digital Products',
    description: 'Four financial mastery prompt packs with 1,000+ side business ideas and proven frameworks for trading, passive income, and wealth building.',
    author: 'Power Prompts',
    url: 'https://powerprompts.beehiiv.com/products/financial-mastery-prompt-bundle',
    tags: ['Template', 'Finance'],
    date: '2026-01-30',
  },
  {
    id: '52-lists-to-see-success',
    title: '52 Lists to See Success',
    category: 'Digital Products',
    description: 'A year of weekly reflection using simple lists to document strengths, service, goals, relationships, and growth.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/52-lists-to-see-success',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'learning-for-eternity',
    title: 'Learning for Eternity: Best BYU Speeches on Learners and Learning',
    category: 'Digital Products',
    description: 'A curated collection of BYU speeches and essays reframing education as spiritual discipleship using the CARPE framework.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/learning-for-eternity-best-byu-speeches-and-articles-on-learners-and-learning',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'god-dwelling-with-his-people',
    title: 'God Dwelling With His People: From Tabernacle To Temple',
    category: 'Digital Products',
    description: 'Discover the beautiful pattern of God\'s presence woven through history, from the Tabernacle to the Temple.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/god-dwelling-with-his-people-from-tabernacle-to-temple',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'heavens-blueprint',
    title: 'Heaven\'s Blueprint: The Tabernacle, Jesus, and the LDS Temple',
    category: 'Digital Products',
    description: 'Explores how the Tabernacle reveals Jesus Christ and modern temple worship, uniting scripture, Christ\'s ministry, and temple ordinances.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/heaven-s-blueprint-the-tabernacle-jesus-and-the-lds-temple',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'old-testament-explained',
    title: 'The Old Testament Explained',
    category: 'Digital Products',
    description: 'A clear guide to the structure, themes, and purpose of every book in the Old Testament.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/the-old-testament-explained-a-clear-guide-to-the-structure-and-themes-of-every-book',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'hebrew-word-of-the-week',
    title: 'The Hebrew Word of the Week for Old Testament Study',
    category: 'Digital Products',
    description: 'Fifty-two foundational Hebrew words from the Bible aligned with the Old Testament CFM curriculum.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/the-hebrew-word-of-the-week-for-old-testament-study',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'old-testament-wrong-name',
    title: 'The Old Testament Has the Wrong Name',
    category: 'Digital Products',
    description: 'Discover the Hebrew Bible as a living covenant of God\'s ongoing faithfulness, revelation, and grace.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/the-old-testament-has-the-wrong-name-discovering-the-living-covenant-behind-the-bible-we-thought-we-knew-2',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'seven-foundational-scriptures',
    title: 'The Seven Foundational Scriptures of the Old Testament',
    category: 'Digital Products',
    description: 'Explores how the Old Testament coheres through seven covenant moments that define God\'s redemptive plan.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/the-seven-foundational-scriptures-that-mark-the-covenantal-landscape-of-the-old-testament-2',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'church-history-tour-2026',
    title: 'Church History Tour May 21-29, 2026',
    category: 'Digital Products',
    description: 'Walk the landscapes where the Restoration unfolded. 9 days of life-changing immersion with Taylor Halverson.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/church-history-tour-may-21-29-2026-with-taylor-halverson',
    tags: ['Course', 'Travel'],
    date: '2026-01-30',
  },
  {
    id: 'unto-a-thousand-generations',
    title: 'Unto a Thousand Generations: The Lord\'s Autobiography of Exodus 34:6-7',
    category: 'Digital Products',
    description: 'Reveals the moment when God reveals His everlasting nature of mercy, truth, and covenant love.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/unto-a-thousand-generations-the-lord-s-autobiography-of-exodus-34-6-7-the-divine-creed-of-mercy-truth-and-covenantal-love',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'bible-as-written-covenant',
    title: 'The Bible as a Written Covenant',
    category: 'Digital Products',
    description: 'Learn to interpret the Bible as the world\'s most sophisticated covenant document using literary, historical, and theological terms.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/the-bible-as-a-written-covenant-how-to-read-the-bible-and-how-to-understand-the-bible-on-its-own-terms',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'tour-israel-2026',
    title: 'Tour Israel with Taylor April 23 - May 2, 2026',
    category: 'Digital Products',
    description: 'Walk where Jesus and prophets taught. Explore Israel\'s landscapes, cultures, and significant religious sites.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/tour-israel-with-taylor-april-23-may-2-2026-deposit',
    tags: ['Course', 'Travel'],
    date: '2026-01-30',
  },
  {
    id: 'yahweh-of-the-south',
    title: 'Yahweh of the South: Wilderness, City and the Origins of Covenant Faith',
    category: 'Digital Products',
    description: 'Examines Israel\'s earliest recollections of Yahweh as a wilderness God revealed in the southern deserts.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/yahweh-of-the-south-wilderness-city-and-the-origins-of-covenant-faith-taylor-halverson-ph-d',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'distributed-holiness',
    title: 'Distributed Holiness: How Scripture Rejects the Monopoly of Sacred Space',
    category: 'Digital Products',
    description: 'Explores how Scripture presents God\'s presence as mobile and relational rather than confined to temples.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/distributed-holiness-how-scripture-rejects-the-monopoly-of-sacred-space-taylor-halverson-ph-d',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'language-of-the-heart',
    title: 'The Language of the Heart',
    category: 'Digital Products',
    description: 'Examines how ancient Israelites understood emotion as central to covenant with God through key Hebrew words.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/the-language-of-the-heart-how-the-bible-and-the-restoration-teach-us-to-feel-like-god-taylor-halverson-ph-d',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'kings-and-kingship',
    title: 'Kings and Kingship in Ancient Israel',
    category: 'Digital Products',
    description: 'Traces Israel\'s monarchy from Saul through Jerusalem\'s fall, examining how covenant faithfulness shaped political power.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/kings-and-kingship-in-ancient-israel-covenant-power-and-the-rise-and-fall-of-israel-s-monarchy-taylor-halverson-ph-d',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'unsung-heroes-bible',
    title: 'Unsung Heroes of the Bible',
    category: 'Digital Products',
    description: 'Explores overlooked biblical figures whose courage quietly shaped biblical history and preserved God\'s covenant.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/unsung-heroes-of-the-bible-faithful-lives-that-preserved-god-s-covenant-when-history-hung-in-the-balance-taylor-halverson-ph-d',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'strange-and-sacred',
    title: 'The Strange and the Sacred: Monsters, Angels, and Symbols',
    category: 'Digital Products',
    description: 'Explores biblical imagery including Leviathan, Nephilim, cherubim, seraphim, and the Ark of the Covenant.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/the-strange-and-the-sacred-monsters-angels-and-symbols-of-the-old-testament-taylor-halverson-ph-d',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: '50-beautiful-hebrew-words',
    title: '50+ Beautiful Hebrew Words for Old Testament Study',
    category: 'Digital Products',
    description: 'Over fifty rich Hebrew words that illuminate the spiritual depth of the Old Testament. No prior Hebrew knowledge required.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/50-beautiful-hebrew-words-to-enhance-your-old-testament-study-taylor-halverson-ph-d',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: '1-nephi-1-new-genesis',
    title: '1 Nephi 1 As a New Genesis',
    category: 'Digital Products',
    description: 'Explores Nephi\'s opening words as a breathtaking act of creation, building on themes from Genesis.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/1-nephi-1-as-a-new-genesis',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'covenant-path-bible-book-of-mormon',
    title: 'The Covenant Path in the Bible & the Book of Mormon',
    category: 'Digital Products',
    description: 'Explores how God\'s covenants shape sacred history and personal discipleship.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/the-covenant-path-in-the-bible-the-book-of-mormon',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'scriptural-insights-doctrine-covenants',
    title: 'Scriptural Insights and Commentary: Doctrine & Covenants',
    category: 'Digital Products',
    description: 'Brings the Restoration to life through clear historical context, faith-centered scholarship, and practical teaching insights.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/scriptural-insights-and-commentary-doctrine-covenants',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'scriptural-insights-old-testament',
    title: 'Scriptural Insights and Commentary: The Old Testament',
    category: 'Digital Products',
    description: 'Unlocks ancient scripture through clear explanations, cultural context, and covenant-focused interpretation.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/scriptural-insights-and-commentary-the-old-testament',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'preparing-tomorrows-missionaries',
    title: 'Preparing Tomorrow\'s Missionaries Today',
    category: 'Digital Products',
    description: 'Equips future disciples with proven, Spirit-guided teaching skills to communicate Christ\'s gospel with clarity and power.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/preparing-tomorrow-s-missionaries-today-teaching-skills-for-disciples-of-christ',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'hear-him',
    title: 'Hear Him: Listening to the Voice of God',
    category: 'Digital Products',
    description: 'Guides readers to recognize and respond to God\'s voice through scriptures, personal stories, and practical exercises.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/hear-him-listening-to-the-voice-of-god-scriptures-and-in-our-lives',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'finding-myself-alone',
    title: 'Finding Myself Alone: Positive Thoughts for LDS Singles',
    category: 'Digital Products',
    description: 'Honest, faith-filled stories from LDS singles, divorcees, and widowed, offering hope and healing for seasons of loneliness.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/finding-myself-alone-positive-thoughts-insights-and-discoveries-of-lds-singles',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'inspiring-book-of-questions',
    title: 'The Inspiring Book of Questions for Learning',
    category: 'Digital Products',
    description: 'Daily companion with thoughtful prompts to deepen self-reflection, ignite curiosity, and sharpen learning habits.',
    author: 'Taylor Halverson',
    url: 'https://insights.taylorhalverson.com/products/the-inspiring-book-of-questions-for-learning',
    tags: ['Ebook', 'Religion'],
    date: '2026-01-30',
  },
  {
    id: 'austin-business-review-founding-member',
    title: 'Founding Member - Austin Business Review',
    category: 'Digital Products',
    description: 'For readers who want to take the conversation further. Exclusive access and deeper engagement with Austin business content.',
    author: 'Austin Business Review',
    url: 'https://austinbusinessreview.beehiiv.com/products/insights-network',
    tags: ['Newsletter', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'radigan-carter-fortress',
    title: 'The Fortress + Private Discord Community',
    category: 'Digital Products',
    description: 'Access to Fortress letters and private Discord for investing, risk management, travel, and life lessons discussions.',
    author: 'Radigan Carter',
    url: 'https://radigancarter.com/products/private-discord',
    tags: ['Newsletter', 'Finance'],
    date: '2026-01-30',
  },
  {
    id: 'algoedge-quant-finance-bootcamp',
    title: 'Quant Finance Bootcamp: Stochastic Models & Option Pricing',
    category: 'Digital Products',
    description: '12-week live program covering stochastic calculus, Black-Scholes, Heston models, volatility smiles, exotic options, and Python implementation.',
    author: 'AlgoEdge Insights',
    url: 'https://algoedgeinsights.beehiiv.com/products/algoedge-insights-quant-finance-bootcamp-stochastic-models-volatility-option-pricing-mastery',
    tags: ['Course', 'Finance'],
    date: '2026-01-30',
  },
  {
    id: 'algoedge-python-trading-strategies',
    title: '30+ Python-Powered Trading Strategies – 2026 Playbook',
    category: 'Digital Products',
    description: '30+ battle-tested algorithmic trading strategies fully coded in Python, backtested, and ready to deploy.',
    author: 'AlgoEdge Insights',
    url: 'https://algoedgeinsights.beehiiv.com/products/algoedge-insights-30-python-powered-trading-strategies-the-complete-2026-playbook',
    tags: ['Playbook', 'Finance'],
    date: '2026-01-30',
  },
  {
    id: 'passive-profits-playbook',
    title: 'Passive Profits Playbook',
    category: 'Digital Products',
    description: 'A comprehensive guide focused on leveraging AI automation to generate passive income streams.',
    author: 'Profit Snack',
    url: 'https://profitsnack.com/products/passive-profits-playbook',
    tags: ['Playbook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'value-engine-blueprint',
    title: 'Value Engine Blueprint',
    category: 'Digital Products',
    description: 'An interactive workbook to design profitable business models with structured frameworks and exercises.',
    author: 'Profit Snack',
    url: 'https://profitsnack.com/products/value-engine-blueprint',
    tags: ['Template', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'bootstrapper-battle-plan-bundle',
    title: 'The Bootstrapper\'s Battle Plan Bundle',
    category: 'Digital Products',
    description: 'Resources for self-funded growth. Workbook and playbook for entrepreneurs building businesses without external funding.',
    author: 'Profit Snack',
    url: 'https://profitsnack.com/products/the-bootstrapper-battle-plan-bundle',
    tags: ['Playbook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'customer-acquisition-system',
    title: 'From Prospect to Profit Playbook',
    category: 'Digital Products',
    description: 'Master every stage of your customer acquisition journey with this complete playbook.',
    author: 'Profit Snack',
    url: 'https://profitsnack.com/products/customer-acquisition-system',
    tags: ['Playbook', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'trust-building-email-sequence',
    title: 'Trust Building Email Sequence',
    category: 'Digital Products',
    description: 'Plug and play email sequence designed to convert subscribers into customers.',
    author: 'Profit Snack',
    url: 'https://profitsnack.com/products/trust-building-email-sequence',
    tags: ['Template', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'ai-ready-transformation',
    title: 'AI Ready Change Management Playbook',
    category: 'Digital Products',
    description: 'Lead digital transformation with confidence and future-proof your business.',
    author: 'Profit Snack',
    url: 'https://profitsnack.com/products/ai-ready-transformation',
    tags: ['Playbook', 'AI'],
    date: '2026-01-30',
  },
  {
    id: 'position-yourself-better',
    title: 'Position Yourself Better. Get Paid More.',
    category: 'Digital Products',
    description: 'A 3-hour course teaching generalists how to articulate and market their unique value proposition to any audience.',
    author: 'Generalist World',
    url: 'https://www.generalistcareer.com/products/position-yourself-better-get-paid-more',
    tags: ['Course', 'Business'],
    date: '2026-01-30',
  },
  {
    id: 'founder-session-tyler-denk',
    title: 'Founder Session w/ Tyler Denk',
    category: 'Digital Products',
    description: 'A private, one-hour coaching session on fundraising, hiring, growth, and scaling a startup with tactical, practical advice.',
    author: 'Big Desk Energy',
    url: 'https://mail.bigdeskenergy.com/products/founder-session-60m',
    tags: ['Course', 'Founders'],
    date: '2026-01-30',
  },
  {
    id: 'private-dealflow-access',
    title: 'Private Dealflow Access (Serious Investors Only)',
    category: 'Digital Products',
    description: 'Access to bi-weekly dealflow opportunities shared via a closed WhatsApp group for qualified investors.',
    author: 'Joe Kinvi',
    url: 'https://joekinvi.beehiiv.com/products/private-dealflow-access-serious-investors-only',
    tags: ['Newsletter', 'Finance'],
    date: '2026-01-30',
  },
];
